#!/bin/bash
export KBUILD_BUILD_USER=GedhangGoreng
export KBUILD_BUILD_HOST=Renyah#NoHost
echo $KBUILD_BUILD_USER
echo $KBUILD_BUILD_HOST
echo -e "done?"
sleep 2s

CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-9.0.0_r61/clang-4691093.tar.gz"

if [ ! -d clang ]; then mkdir clang && curl -Lsq "${CLANG_URL}" -o clang.tgz && tar -xzf clang.tgz -C clang; fi
PATH="~/clang/bin"

make CC=clang ARCH=arm64 O=~/out oppo6762_18540_defconfig
make CC=clang LLVM=1 ARCH=arm64 O=~/out -j16 \
        HEADER_ARCH=arm64 \
        SUBARCH=arm64 \
        CXX=c++ \
        AR=llvm-ar \
        NM=llvm-nm \
        OBJDUMP=llvm-objdump \
        STRIP=llvm-strip \
        READELF=llvm-readelf \
        HOSTCXX=clang++ \
        HOSTAR=llvm-ar \
        LLVM_IAS=1 \
      	CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
        CLANG_TRIPLE=aarch64-linux-gnu-
